const container = document.querySelector('.container');
const insertHeading = document.getElementById('insertHeading');
const insertKeyCode = document.getElementById('insertKeyCode');
const insertKeys = document.getElementById('insertKeys');

window.addEventListener('keydown', (event) => {
  container.classList.add('active');
  insertHeading.innerHTML = `
  <h1>KeyboardEvent keyCode Viewer</h1>
  `,
  insertKeyCode.innerHTML=`
  <div class="key">
  ${event.which}
  <small>event.which <a href="https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/which" target="_blank">(deprecated)</a></small>
  </div>
  `,
  insertKeys.innerHTML = `
  <div class="key">
  ${event.key === ' ' ? 'Space' : event.key} 
  <small>event.key</small>
</div>
<div class="key">
  ${event.code}
  <small>event.code</small>
</div>
<div class="key">
  ${event.location}
  <small>event.location</small>
</div>
<div class="key">
  ${event.repeat}
  <small>event.repeat</small>
</div>
  `
})


// https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/KeyboardEvent
// KeyboardEvent.key returns the value of the key pressed by the user, taking into consideration the state of modifier keys such as Shift as well as the keyboard locale and layout.
// KeyboardEvent.location returns an unsigned long representing the location of the key on the keyboard or other input device.
// KeyboardEvent.code represents a physical key on the keyboard (as opposed to the character generated by pressing the key). 
// KeyboardEvent.repeat returns a Boolean that is true if the given key is being held down such that it is automatically repeating.
// Inspiration from https://keycode.info/